### ISSUE TITLE
Doesn't open file dialog

### ISSUE THREAD

**Issue by henon** [jannhama/vuetify-upload-btn#1]
Hey, I just tried out your button with latest vue and vuetify and it doesn't open the file selection dialog. Here is how I changed the template to make it work:

`
 <template>
  <v-btn dark class="btn--dark-flat-focused jbtn-file" @click="$refs.fileInput.click()">
    {{ title }}<input id="selectFile" ref="fileInput" type="file" v-on:change="fileSelected">
  </v-btn>
 </template>
`

**Comment by jannhama** [comment]
Which vue & vuetify versions you're using ? Which browser ? I tried with Vue 2.5.2 and Vuetify 1.0.3 using Chrome and it works.

**Comment by jannhama** [comment]
Ok, doesn't work in Firefox but your fix does. Chrome acts weird way. Will check.

**Comment by henon** [comment]
Yeah, I was testing with Firefox.  Let me know about your final solution that works in Chrome too. Thanks!

**Comment by jannhama** [comment]
Seems to be likely an issue with v-btn. For Chrome your solution fires click event two times, for Firefox only once. Easiest solution would be to change v-btn to plain div using original implementation (without click handler).

**Comment by jannhama** [comment]
Fixed by changing v-btn to div.

**Comment by andreshg112** [comment]
With `div`, It doesn't look like a button even if I add the class. I noticed that btn and btn-primary don't exist. I'm using `{"vue": "2.5.16", "vuetify": "1.1.1"}`

template:
![image](https://user-images.githubusercontent.com/15859884/42826197-72c145aa-89a9-11e8-9e71-948a0f44521f.png)

tag:
![image](https://user-images.githubusercontent.com/15859884/42826231-882a008a-89a9-11e8-8b34-ec84a91c0d3c.png)

view:
![image](https://user-images.githubusercontent.com/15859884/42826244-9038daa8-89a9-11e8-8618-829c4dead3c4.png)

**Comment by andreshg112** [comment]
I solved it by doing this in your component:
```
<template>
  <v-btn tag="div" class="jbtn-file">
    {{ title }}
    <input type="file" v-on:change="fileSelected" :multiple="multiple">
  </v-btn>
</template>
```

**Comment by jannhama** [comment]
I'll try it later on. Will integrate if works fine :)
